import {
  DiscoverResponse,
  StorytellerResponse,
  LocalEvent,
  ItineraryResponse,
  PersonaId,
} from "@/lib/types";

export const MOCK_DISCOVER_DATA: Record<string, DiscoverResponse> = {
  kyoto: {
    destination: "Kyoto",
    country: "Japan",
    tagline: "The Eternal Capital of Temples, Gardens & Geisha Heritage",
    description: "Kyoto served as Japan's imperial capital for over a millennium. It remains the cultural heart of the nation, where ancient Shinto shrines coexist with tranquil Zen gardens, traditional wooden machiya townhouses, and the living arts of tea ceremonies and silk weaving.",
    heroImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    landmarks: [
      {
        id: "fushimi-inari",
        name: "Fushimi Inari Taisha",
        category: "sacred",
        description: "An iconic Shinto shrine dedicated to Inari, the god of rice and agriculture, famous for its thousands of vermilion torii gates winding up the sacred Mount Inari.",
        historicalSignificance: "Founded in 711 AD before Kyoto became the capital, serving as a beacon for merchants and farmers seeking prosperity.",
        bestTimeToVisit: "Early morning (6:00 AM) or dusk to experience the mystical atmosphere without crowds.",
        image: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=800&q=80",
        tags: ["Shinto", "Torii Gates", "Sacred Mountain", "Ancient Architecture"],
      },
      {
        id: "kiyomizu-dera",
        name: "Kiyomizu-dera Temple",
        category: "architecture",
        description: "A celebrated Buddhist temple suspended on massive wooden pillars overlooking Kyoto, built entirely without a single nail.",
        historicalSignificance: "Established in 778 AD, it is dedicated to Kannon, the goddess of mercy. The wooden stage offers panoramic views of cherry blossoms and autumn maple leaves.",
        bestTimeToVisit: "Late afternoon during sunset or spring/autumn illumination evenings.",
        image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
        tags: ["UNESCO Heritage", "Wooden Stage", "Otowa Waterfall", "Buddhism"],
      },
      {
        id: "kinkaku-ji",
        name: "Kinkaku-ji (Golden Pavilion)",
        category: "heritage",
        description: "A Zen Buddhist temple whose top two floors are completely covered in brilliant gold leaf, reflecting serenely in the Mirror Pond.",
        historicalSignificance: "Originally built in 1397 as a retirement villa for Shogun Ashikaga Yoshimitsu, later converted into a Zen temple.",
        bestTimeToVisit: "Mid-morning when sunlight catches the gold leaf and reflects on the calm pond.",
        image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
        tags: ["Zen Garden", "Gold Leaf", "Muromachi Period", "Reflection Pond"],
      },
      {
        id: "arashiyama-bamboo",
        name: "Arashiyama Bamboo Grove",
        category: "nature" as any,
        description: "A soaring natural pathway of dense green bamboo stalks that sway gently in the wind, producing a mesmerizing rustling sound.",
        historicalSignificance: "Bamboo has been revered in Japanese folklore as a protector against evil spirits and a symbol of resilience.",
        bestTimeToVisit: "Before 7:30 AM to hear the natural wind symphonies undisturbed.",
        image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
        tags: ["Soundscape Heritage", "Nature Trail", "Sagano", "Zen Peace"],
      },
    ],
    hiddenGems: [
      {
        id: "pontocho-alley",
        name: "Pontocho Traditional Alleyway",
        location: "Running parallel to the Kamogawa River between Shijo and Sanjo",
        secretTip: "Look for lanterns with a plover (chidori) bird symbol—these denote authentic traditional teahouses where Geiko and Maiko entertain.",
        culturalRelevance: "One of Kyoto's five traditional Hanamachi (geisha districts), preserving centuries-old culinary and performing arts.",
        image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
        category: "gastronomy",
      },
      {
        id: "nishijin-weaving",
        name: "Nishijin Textile Artisan Studio",
        location: "Kamigyo Ward, northwestern Kyoto",
        secretTip: "Visit family-run workshops like Orinasu-kan to watch master weavers operate traditional wooden Jacquard handlooms.",
        culturalRelevance: "Nishijin-ori weaving dates back over 1,200 years, producing ornate silk brocades used in imperial Kimonos and Obi sashes.",
        image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
        category: "artisan",
      },
      {
        id: "otagi-nenbutsuji",
        name: "Otagi Nenbutsu-ji Temple of 1,200 Rakan",
        location: "Arashiyama Hills, north of the main tourist trails",
        secretTip: "Examine the faces of the 1,200 moss-covered stone statues—every single one has a unique facial expression, from laughing to drinking sake.",
        culturalRelevance: "Carved by ordinary citizens under the guidance of sculptor-monk Kocho Nishimura between 1981 and 1991 to heal the temple after typhoon damage.",
        image: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=800&q=80",
        category: "folklore",
      },
    ],
    etiquette: [
      {
        category: "sacred_sites",
        title: "Temizuya Purification Ritual",
        description: "Before entering Shinto shrines, perform the cleansing ritual at the stone water fountain.",
        doList: [
          "Take the wooden dipper in your right hand and wash your left hand.",
          "Switch hands and wash your right hand.",
          "Pour water into your left palm to rinse your mouth gently (never drink directly from the dipper).",
          "Tilt the dipper vertically so remaining water washes the handle for the next visitor.",
        ],
        dontList: [
          "Never put the dipper directly to your mouth.",
          "Do not throw coins forcefully into the offering box; toss them gently.",
          "Avoid walking directly down the center of the torii pathway (the Sei-chū), which is reserved for the deity.",
        ],
      },
      {
        category: "greeting",
        title: "The Art of Bowing (Ojigi)",
        description: "Bowing is the foundational expression of respect, gratitude, and greeting in Japanese society.",
        doList: [
          "Perform a gentle 15-degree nod (Eshaku) for casual greetings in shops and cafes.",
          "Use a 30-degree bow (Keirei) when greeting temple hosts or elder artisans.",
          "Keep your back straight and gaze downward during the bow.",
        ],
        dontList: [
          "Do not combine shaking hands with bowing simultaneously.",
          "Do not maintain direct eye contact while bowing.",
        ],
      },
      {
        category: "tipping",
        title: "Tipping Culture & Hospitality (Omotenashi)",
        description: "Japan prides itself on Omotenashi—selfless hospitality without expectation of extra reward.",
        doList: [
          "Express heartfelt appreciation by saying 'Arigatou gozaimasu' or 'Gochisousama deshita' after a meal.",
          "Pay cash or cards directly at the cashier tray rather than handing money directly to servers.",
        ],
        dontList: [
          "NEVER leave a cash tip on a restaurant table or taxi seat; waitstaff will run after you thinking you forgot your money.",
        ],
      },
    ],
    heritage: [
      {
        title: "Machiya Townhouse Preservation",
        endangeredStatus: "Vulnerable",
        preservationEffort: "Historic wooden machiya residences are being lost to modern concrete construction due to high inheritance taxes and maintenance costs.",
        howToSupport: "Stay in certified restored machiya guesthouses, dine in traditional machiya cafes, and support local preservation trusts like Kyomachiya Council.",
        indigenousCommunity: "Kyoto Traditional Craftsmen & Carpenters (Miyadaiku)",
      },
      {
        title: "Nishijin Silk Weaving Apprenticeships",
        endangeredStatus: "Critical",
        preservationEffort: "The aging population of master weavers threatens the transmission of complex handloom techniques for ceremonial Kimonos.",
        howToSupport: "Purchase authentic handmade textiles directly from studio cooperatives rather than mass-produced synthetic souvenirs.",
        indigenousCommunity: "Nishijin Weaving Guild of Kamigyo",
      },
    ],
  },
  oaxaca: {
    destination: "Oaxaca",
    country: "Mexico",
    tagline: "The Soul of Zapotec Traditions, Alebrije Folk Art & Ancestral Mezcal",
    description: "Nestled in the Sierra Madre mountains, Oaxaca is Mexico's undisputed culinary and cultural capital. Here, vibrant Zapotec and Mixtec heritage thrives in colorful colonial streets, ancient pyramids, bustling indigenous markets, and the smoky aroma of slow-cooked Mole and artisan Mezcal.",
    heroImage: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=1200&q=80",
    landmarks: [
      {
        id: "monte-alban",
        name: "Monte Albán Archaeological Site",
        category: "heritage",
        description: "The ancient Zapotec capital built on a flattened mountain top 400 meters above the Oaxaca Valley, featuring monumental pyramids and astronomical observatories.",
        historicalSignificance: "Inhabited for over 1,500 years by Olmecs, Zapotecs, and Mixtecs, serving as the political and ceremonial epicenter of Mesoamerica.",
        bestTimeToVisit: "Early morning upon opening at 8:00 AM to enjoy the mystical valley fog and avoid the midday sun.",
        image: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=800&q=80",
        tags: ["Zapotec Heritage", "Pyramids", "UNESCO", "Mesoamerica"],
      },
      {
        id: "santo-domingo",
        name: "Templo de Santo Domingo de Guzmán",
        category: "architecture",
        description: "A Baroque masterpiece founded by Dominican friars in 1572, renowned for its breathtaking gilded interior covered in intricate gold leaf reliefs.",
        historicalSignificance: "The former monastery now houses the Oaxaca Cultural Museum, containing the legendary Mixtec gold treasures discovered in Tomb 7 at Monte Albán.",
        bestTimeToVisit: "Late afternoon when the golden sunlight bathes the limestone facade and surrounding botanical garden.",
        image: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=800&q=80",
        tags: ["Baroque Architecture", "Gold Leaf", "Dominican", "Ethnobotanical Garden"],
      },
    ],
    hiddenGems: [
      {
        id: "san-martin-tilcajete",
        name: "San Martín Tilcajete Alebrije Workshops",
        location: "23 km south of Oaxaca City along Highway 175",
        secretTip: "Visit the workshop of Jacobo and María Ángeles to witness the complete transformation of copal wood into fantastical mythical beasts painted with natural mineral dyes.",
        culturalRelevance: "Alebrijes embody Zapotec nahual beliefs—spiritual animal protectors that guide human souls from birth.",
        image: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=800&q=80",
        category: "artisan",
      },
      {
        id: "teotitlan-weavers",
        name: "Teotitlán del Valle Natural Dye Weavers",
        location: "Foot of the Sierra Juárez mountains, 30 km east of Oaxaca",
        secretTip: "Ask to see the preparation of Grana Cochineal—an ancient parasitic insect that lives on nopal cacti and produces intense carmine red and purple dyes when mixed with lime or lemon.",
        culturalRelevance: "Zapotec weaving families use foot-pedal looms introduced in the 16th century to weave geometric rugs depicting ancestral Zapotec diamonds and rain gods.",
        image: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=800&q=80",
        category: "artisan",
      },
    ],
    etiquette: [
      {
        category: "greeting",
        title: "Respecting Indigenous Elders & Communities",
        description: "Oaxaca is home to 16 distinct Indigenous ethnic groups with proud customs and community self-governance (Usos y Costumbres).",
        doList: [
          "Always greet shopkeepers and market vendors with a polite 'Buenos días' or 'Buenas tardes' before asking prices.",
          "Ask explicit permission before photographing indigenous weavers, artisans, or ceremonial dances.",
          "Pay fair prices in artisan workshops; remember that a single handwoven rug or carved Alebrije can take 3 to 6 months to complete.",
        ],
        dontList: [
          "Never treat religious festivals or Day of the Dead (Día de los Muertos) cemeteries as photo props or theme parties.",
          "Avoid aggressive haggling; small discounts are acceptable, but devaluing artisan labor is offensive.",
        ],
      },
    ],
    heritage: [
      {
        title: "Ancestral Wild Agave & Mezcal Sustainability",
        endangeredStatus: "Vulnerable",
        preservationEffort: "High global demand for Mezcal is depleting wild agave varieties (such as Tobalá, Tepeztate, and Arroqueño) that take 12 to 25 years to mature in the wild.",
        howToSupport: "Visit sustainable family palenques (distilleries) that practice reforestation and seed banking, and always choose certified ancestral or artisanal brands.",
        indigenousCommunity: "Zapotec & Mixtec Maestro Mezcaleros of Matatlán",
      },
    ],
  },
};

export const MOCK_STORYTELLER_DATA: Record<PersonaId, StorytellerResponse> = {
  historian: {
    title: "The Shogun's Golden Vision: The Muromachi Chronicle",
    personaName: "Lord Kenjiro, 15th-Century Imperial Court Historian",
    timePeriod: "Muromachi Period (1397 AD)",
    storyContent: "Hark, traveler! You stand before Kinkaku-ji, the Golden Pavilion, which shines like a celestial palace fallen to our mortal earth. When my master, the third Ashikaga Shogun Yoshimitsu, commissioned this retirement villa in the year 1397, the realm was weary from decades of civil strife. He sought to create an earthly pure land—a symbol of supreme harmony connecting our impermanent world to the Western Paradise of Amida Buddha.\n\nObserve closely how the architecture unites three distinct eras of our empire: the ground floor speaks of simple Heian residential elegance; the second floor honors samurai warrior austerity; while the crowning third story, completely gilded in pure gold leaf and topped with a bronze phoenix, reaches toward Zen transcendence. Even when fire consumed this structure centuries later, the people rebuilt every timber and gold sheet with unwavering reverence, proving that physical beauty may perish, but cultural memory is immortal.",
    audioScript: "Hark, traveler! You stand before Kinkaku-ji, the Golden Pavilion. When my master, Shogun Yoshimitsu, commissioned this villa in 1397, he sought to create an earthly pure land—a symbol of supreme harmony connecting our impermanent world to the Western Paradise of Amida Buddha.",
    historicalFact: "The top two floors are covered with over 20 kilograms of pure gold leaf, which is carefully reapplied every few decades by traditional Kyoto artisans using bamboo tweezers.",
    culturalProverb: {
      original: "Mono no aware (物の哀れ)",
      translation: "The pathos of things",
      meaning: "A deep, empathetic appreciation of the fleeting, impermanent beauty of nature and human existence.",
    },
    tags: ["Ashikaga Shogunate", "Zen Buddhism", "Architecture", "Imperial Court"],
  },
  artisan: {
    title: "The Singing Wood of Nishijin Looms",
    personaName: "Master Haru, 5th-Generation Silk Weaver",
    timePeriod: "Edo Period Traditional Craftsmanship",
    storyContent: "Welcome to my humble workshop, honored guest. Do you hear that rhythmic clack-clack-thump echoing through the wooden beams? That is the heartbeat of Nishijin-ori weaving, an art my ancestors have guarded for over five generations. Every thread of dyed silk you see here was spun by silkworms fed on tender mulberry leaves, then boiled in pure Kyoto spring water.\n\nTo weave a single ceremonial Kimono sash, an Obi, requires over ten thousand silk threads precisely aligned on this wooden Jacquard handloom. Look at this golden dragon motif—we insert thin strips of genuine gold paper coated in lacquer directly between the silk wefts. It takes me an entire day of unbroken focus to weave just five centimeters of cloth. When you wear fabric made by human hands, you carry the spirit, patience, and devotion of the artisan within the weave.",
    audioScript: "Welcome to my humble workshop, honored guest. Do you hear that rhythmic clack-clack-thump echoing through the wooden beams? That is the heartbeat of Nishijin-ori weaving. It takes me an entire day of unbroken focus to weave just five centimeters of cloth.",
    historicalFact: "Nishijin weavers historically used fingernail filing techniques (Tsumekaki Hon-tsuzureshori), where artisans file their own thumbnails into comb-like ridges to physically push gold threads into the fabric.",
    culturalProverb: {
      original: "Ichigo ichie (一期一会)",
      translation: "One time, one meeting",
      meaning: "Treasure every encounter and creative moment, for it will never recur in exactly the same way again.",
    },
    tags: ["Silk Weaving", "Master Craftsmanship", "Nishijin", "Living Heritage"],
  },
  bard: {
    title: "The Kitsune of Sacred Mount Inari",
    personaName: "Old Ren, Wandering Folklore Storyteller & Shamisen Bard",
    timePeriod: "Timeless Folklore & Myth",
    storyContent: "Gather close around the lantern light, traveler, and listen to the whisper of the wind through the vermilion gates! Why do thousands of red torii archways climb into the shadowy forests of Mount Inari? Legend whispers that centuries ago, a humble rice farmer shot an arrow at a floating rice cake. As the arrow struck, the cake magically transformed into a radiant white swan and flew to the peak of this mountain, where wild rice began to grow abundantly out of the bare rock!\n\nEver since that blessed day, the great deity Inari Okami has dwelled on these slopes, guarded by mystical white foxes known as Kitsune. As you walk through the tunnel of gates at twilight, keep your eyes on the stone fox statues holding scrolls, keys, and jewels in their jaws. But beware! If you hear a soft rustling in the bamboo and see a pair of golden eyes blinking in the shadows, do not stray from the path—for the Kitsune love to test the purity of a traveler's heart!",
    audioScript: "Gather close around the lantern light, traveler! Why do thousands of red torii archways climb into the shadowy forests of Mount Inari? Legend whispers that centuries ago, the great deity Inari Okami chose these slopes, guarded by mystical white foxes known as Kitsune.",
    historicalFact: "The vermilion color (Aka) of the torii gates is made from cinnabar mineral pigment, traditionally believed to repel evil spirits and preserve the wood from decay.",
    culturalProverb: {
      original: "Onko chishin (温故知新)",
      translation: "Discovering new truth by studying the past",
      meaning: "By exploring ancient myths and historical traditions, we gain deep wisdom to guide our present lives.",
    },
    tags: ["Shinto Mythology", "Kitsune Foxes", "Torii Gates", "Folk Legends"],
  },
  anthropologist: {
    title: "The Living Sanctuary of Gion's Geiko Culture",
    personaName: "Dr. Elena Vance, Modern Cultural Anthropologist",
    timePeriod: "Contemporary Heritage Analysis (2026)",
    storyContent: "As we stand on the cobblestones of Hanamikoji Street in Kyoto's Gion district, we are observing one of the world's most misunderstood and resilient matriarchal arts communities. In Western pop culture, Geisha are often inaccurately stereotyped, but from an anthropological lens, they are elite conservators of Japan's classical performing arts—including Shamisen music, Kyo-mai dance, calligraphic poetry, and the formal tea ceremony.\n\nA young woman entering a Okiya (geisha lodging) undergoes rigorous apprenticeships as a Maiko for up to five years, learning over 50 traditional songs and mastering intricate conversational etiquette. Notice how the community is self-regulated through strict lineages of mentorship between older Geiko ('mothers' and 'big sisters') and younger trainees. By supporting ethical cultural tours and respecting their privacy as they walk to evening engagements, travelers play a crucial role in preventing overtourism from eroding this fragile cultural ecosystem.",
    audioScript: "As we stand on the cobblestones of Gion, we are observing one of the world's most resilient matriarchal arts communities. Geiko and Maiko are elite conservators of Japan's classical performing arts, undergoing rigorous apprenticeships to master centuries-old traditions.",
    historicalFact: "Kyoto geisha refer to themselves as 'Geiko' (woman of art) rather than 'Geisha' (person of art), distinguishing their specialized Kyoto court lineage from Tokyo traditions.",
    culturalProverb: {
      original: "Wabi-sabi (侘寂)",
      translation: "Beauty in imperfection and rustic simplicity",
      meaning: "Finding profound spiritual fulfillment in modest, unadorned, and weathered cultural artifacts.",
    },
    tags: ["Matriarchal Arts", "Ethical Tourism", "Geiko Heritage", "Gion"],
  },
};

export const MOCK_EVENTS_DATA: LocalEvent[] = [
  {
    id: "gion-matsuri",
    title: "Gion Matsuri Grand Procession (Yamaboko Junko)",
    dateRange: "July 1 - July 31 (Main Parade: July 17)",
    category: "festival",
    description: "One of Japan's most celebrated festivals dating back to 869 AD, originally held to appease plague deities. Features massive wooden floats (Yamaboko) weighing up to 12 tons, decorated with rare Persian and Nishijin tapestries, pulled through downtown Kyoto without a single nail.",
    location: "Shijo and Kawaramachi Avenues, Central Kyoto",
    authenticityScore: 99,
    ticketInfo: "Free street viewing; reserved covered seating available from ¥4,000 via Kyoto City Tourism Federation.",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "gozan-okuribi",
    title: "Gozan no Okuribi (Daimonji Fire Ritual)",
    dateRange: "August 16 (Evening at 8:00 PM)",
    category: "ritual",
    description: "A breathtaking Buddhist ritual concluding the Obon festival of honoring ancestors. Giant bonfires shaped like kanji characters and symbols (including 'Dai' meaning great) are ignited on five mountains surrounding Kyoto to guide ancestral spirits back to the spiritual realm.",
    location: "Mount Daimonji & Surrounding Kyoto Mountains (Best viewed from Kamogawa River banks)",
    authenticityScore: 98,
    ticketInfo: "Free community gathering along the Kamogawa riverbanks.",
    image: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "tea-ceremony-workshop",
    title: "Way of Tea (Chado) Master Class in Daitoku-ji Temple",
    dateRange: "Every Tuesday, Thursday & Saturday morning",
    category: "workshop",
    description: "An intimate, hands-on workshop led by a certified Urasenke tea master inside a tranquil 400-year-old Zen sub-temple. Participants learn the spiritual philosophy of harmony, respect, purity, and tranquility while preparing ceremonial matcha with bamboo whisks.",
    location: "Zuiho-in Sub-temple, Daitoku-ji Zen Complex, Kita Ward",
    authenticityScore: 96,
    ticketInfo: "¥6,500 per person (includes traditional wagashi seasonal sweets and ceramic bowl souvenir). Advance booking required.",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "guelaguetza-oaxaca",
    title: "Guelaguetza Festival of the Indigenous Peoples",
    dateRange: "Last two Mondays of July",
    category: "music_dance",
    description: "Oaxaca's most magnificent indigenous gathering, where 16 indigenous ethnic communities from the seven regions of the state converge at the open-air auditorium on Cerro del Fortín to share ancestral music, traditional dances, and harvest gifts with visitors.",
    location: "Auditorio Guelaguetza, Cerro del Fortín, Oaxaca City",
    authenticityScore: 100,
    ticketInfo: "Sections C & D are free for general public; Sections A & B reserved seating around $45-$60 USD.",
    image: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=800&q=80",
  },
];

export const MOCK_ITINERARY_DATA: ItineraryResponse = {
  title: "3-Day Kyoto Cultural Immersion: From Sacred Temples to Hidden Artisan Studios",
  destination: "Kyoto, Japan",
  totalDays: 3,
  days: [
    {
      dayNumber: 1,
      theme: "Sacred Gateways & Zen Tranquility",
      morningActivity: {
        time: "07:00 - 10:00",
        title: "Fushimi Inari Sunrise Pilgrimage",
        description: "Hike through the thousands of vermilion torii gates on Mount Inari before the midday heat and tourist crowds arrive.",
        culturalSignificance: "Experience Shinto nature worship and observe traditional farmers leaving sake and fried tofu offerings for the Inari deity.",
        accessibilityNote: "Lower shrine paths are fully paved and wheelchair accessible; upper mountain loop requires climbing stone steps.",
      },
      afternoonActivity: {
        time: "13:00 - 16:30",
        title: "Kiyomizu-dera & Sannenzaka Heritage Walk",
        description: "Explore the UNESCO wooden temple stage and stroll down the preserved Edo-period stone-paved streets of Ninenzaka and Sannenzaka.",
        culturalSignificance: "Admire traditional timber joinery architecture without nails and browse centuries-old ceramic shops selling Kiyomizu-yaki pottery.",
      },
      eveningActivity: {
        time: "18:00 - 20:30",
        title: "Pontocho Lantern Stroll & Traditional Kaiseki Dinner",
        description: "Walk along the atmospheric narrow alleyway beside the Kamogawa River, dining at a historic riverside restaurant with Kawadoko outdoor seating.",
        culturalSignificance: "Savor Kyoto's refined multi-course Kaiseki cuisine, which highlights hyper-seasonal local vegetables (Kyo-yasai) and culinary aesthetics.",
      },
      culinaryRecommendation: {
        dishName: "Kyo-Kaiseki Seasonal Multi-Course Meal",
        description: "An artistic procession of sashimi, simmered tofu, grilled seasonal fish, and clear dashi broths presented on handcrafted lacquerware.",
        whereToFind: "Pontocho Robin or Izusen in Daitoku-ji.",
      },
      localInteractionTip: "When receiving a bowl of matcha or broth, bow slightly to the server and hold the vessel with both hands to show respect for the potter's craftsmanship.",
    },
    {
      dayNumber: 2,
      theme: "Living Textiles & Golden Pavilion Wonders",
      morningActivity: {
        time: "08:30 - 11:30",
        title: "Kinkaku-ji (Golden Pavilion) & Ryoan-ji Zen Rock Garden",
        description: "Witness the morning sun gleaming off Kinkaku-ji's gold leaf, followed by meditative contemplation at Japan's most famous dry landscape (Karesansui) garden at Ryoan-ji.",
        culturalSignificance: "Contemplate the 15 mysterious stones at Ryoan-ji, arranged so that from any vantage point, at least one stone is always hidden from view—teaching humility.",
      },
      afternoonActivity: {
        time: "13:30 - 16:30",
        title: "Nishijin Textile Center & Private Handloom Studio Visit",
        description: "Meet master silk weavers in Kamigyo Ward and try your hand at weaving on a traditional wooden loom.",
        culturalSignificance: "Directly support one of Kyoto's most endangered heritage professions and learn how obi sashes are crafted for ceremonial Kimonos.",
      },
      eveningActivity: {
        time: "18:30 - 21:00",
        title: "Gion Cultural Arts Performance at Gion Corner",
        description: "Attend an authentic evening showcase featuring seven traditional performing arts: Kyo-mai dance, Bunraku puppet theater, Gagaku court music, and Kyogen comedy.",
        culturalSignificance: "Gain an accessible overview of classical Japanese theater and music traditions preserved by Kyoto's arts guilds.",
      },
      culinaryRecommendation: {
        dishName: "Yudofu (Simmered Silken Tofu in Kelp Broth)",
        description: "Delicate Kyoto tofu warmed in pure kelp dashi, served with shaved bonito flakes, green onions, and sweet soy dipping sauce.",
        whereToFind: "Okutan Kiyomizu or Junsei near Nanzen-ji Temple.",
      },
      localInteractionTip: "In artisan studios, always ask 'Shashin wo tottemo ii desu ka?' (May I take a photo?) before snapping pictures of weavers or delicate textiles.",
    },
    {
      dayNumber: 3,
      theme: "Bamboo Forests & Tea Ceremony Mastery",
      morningActivity: {
        time: "07:30 - 10:30",
        title: "Arashiyama Bamboo Grove & Tenryu-ji Landscape Garden",
        description: "Walk through the towering green bamboo trail, then explore the 14th-century Zen garden designed by landscape master Muso Soseki.",
        culturalSignificance: "Experience Shakkei (borrowed scenery), where the distant Arashiyama mountains are seamlessly integrated into the temple garden design.",
      },
      afternoonActivity: {
        time: "13:00 - 15:30",
        title: "Authentic Way of Tea (Chado) Experience",
        description: "Participate in a private tea ceremony in a historic tatami teahouse, learning the graceful etiquette of preparing and drinking ceremonial matcha.",
        culturalSignificance: "Embrace the philosophy of Ichigo Ichie (one time, one meeting) and appreciate the seasonal flower arrangement (Chabana) and hanging scroll in the alcove.",
      },
      eveningActivity: {
        time: "17:00 - 19:30",
        title: "Nishiki Market Culinary Exploration & Sake Tasting",
        description: "Wander down 'Kyoto's Kitchen', a narrow five-block shopping street lined with over a hundred stalls selling pickles, dried seafood, Japanese sweets, and artisanal sake.",
        culturalSignificance: "Interact with multi-generational food purveyors and sample local delicacies that form the backbone of traditional home cooking.",
      },
      culinaryRecommendation: {
        dishName: "Matcha Parfait & Warabimochi",
        description: "A decadent traditional sweet featuring Uji matcha ice cream, chewy bracken-starch mochi dusted with roasted soybean flour (kinako), and sweet azuki beans.",
        whereToFind: "Tsujiri Tea House or Gion Tsujiri on Shijo Avenue.",
      },
      localInteractionTip: "When sampling food at Nishiki Market, eat your snack directly in front of the stall where you bought it; walking while eating is considered impolite.",
    },
  ],
  sustainabilitySummary: "This itinerary directly promotes sustainable cultural tourism by prioritizing early morning visits to reduce peak crowd congestion, supporting locally owned machiya dining, and routing travel through authentic artisan cooperatives where 100% of purchase proceeds go to endangered craft guilds.",
};
